#!/usr/bin/env bash
# Shared setup for the DS-ViRe benchmark steps. Sourced, never executed.
#
# Both benchmarks used to run on the self-hosted `tokito-vps` GitHub Actions
# runner, which read two fixed host paths directly. That runner is being
# decommissioned; this file is what both step scripts source so the mapping
# from GitHub Actions concepts to their Buildkite equivalents lives in one
# place instead of being duplicated:
#
#   ${{ github.workspace }}   -> $BUILDKITE_BUILD_CHECKOUT_PATH
#   ${GITHUB_SHA}             -> $BUILDKITE_COMMIT
#   $RUNNER_TEMP              -> mktemp'd $BENCHMARK_SCRATCH (see below)
#   setup-python (3.12)       -> dropped; uv provisions the interpreter
#
# shellcheck shell=bash

set -euo pipefail

# One knob for where the warm corpus cache and pinned OpenCLIP weights live,
# instead of the path being spelled out separately in both step scripts.
# Defaults to where the Buildkite build host actually has them restored;
# override only to point at a different mount for local testing.
TOKITO_BENCHMARK_ASSETS="${TOKITO_BENCHMARK_ASSETS:-/opt/tokito-benchmark-assets}"
export TOKITO_BENCHMARK_ASSETS

BENCHMARK_CORPUS="$TOKITO_BENCHMARK_ASSETS/.dsvire-benchmark-sources"
export BENCHMARK_CORPUS

# The corpus is a warm, shared cache that both benchmarks read (one of them
# concurrently downloads into a *separate* scratch dir, never into this one).
# Nothing in either step script is allowed to write here — it is restored
# from a backup archive, not regenerated by CI, and a run that mutated it
# would poison the next run's cache for everyone.
require_benchmark_corpus() {
  if [ ! -d "$BENCHMARK_CORPUS" ]; then
    cat >&2 <<EOF
missing benchmark corpus directory: $BENCHMARK_CORPUS

The warm datasheet corpus cache is not present on this build host. Restore it
from the archive in tokitostaging:/opt/tokito-backups/benchmark-assets/.
EOF
    exit 1
  fi
}

# openclip-query.sh calls this with the exact pinned weights path; nothing
# else needs it.
require_benchmark_model() {
  local weights="$1"
  if [ ! -f "$weights" ]; then
    cat >&2 <<EOF
missing benchmark model weights: $weights

The pinned OpenCLIP weights are not present on this build host. Restore them
from the archive in tokitostaging:/opt/tokito-backups/benchmark-assets/.
EOF
    exit 1
  fi
}

# The workflows pinned astral-sh/setup-uv to version 0.12.3 and let it manage
# Python 3.12 itself — there was never a separate setup-python step for the
# benchmark jobs' interpreter. Buildkite has no setup-uv action, so the build
# host's `uv` has to already be that exact version. Fail loudly rather than
# silently installing or upgrading uv: a benchmark step changing its own
# toolchain out from under a pinned run is exactly the kind of drift the
# version pin exists to prevent.
require_uv_version() {
  local want="0.12.3" got
  if ! command -v uv >/dev/null 2>&1; then
    echo "uv is not on PATH; the build agent must provision uv ${want}" >&2
    exit 1
  fi
  got="$(uv --version | awk '{print $2}')"
  if [ "$got" != "$want" ]; then
    echo "uv ${got} is on PATH, need exactly ${want} (the version astral-sh/setup-uv pinned)" >&2
    exit 1
  fi
}

# Persistent under the agent's home, unlike the per-build checkout. This is
# what replaces `enable-cache: true` on setup-uv: the frozen visual/openclip
# runtime (torch, torchvision, open_clip_torch, ...) is large enough that
# re-downloading it on every dispatch would make an occasional benchmark
# expensive to run at all.
UV_CACHE_DIR="${UV_CACHE_DIR:-$HOME/.cache/tokito-dsvire-benchmark-uv}"
mkdir -p "$UV_CACHE_DIR"
export UV_CACHE_DIR

# Buildkite gives no guaranteed-clean scratch directory the way GitHub
# Actions' $RUNNER_TEMP does (a fresh, runner-owned temp dir for the job).
# mktemp our own per step and remove it on exit, so a benchmark's
# download-cache scratch can never linger or collide with the next run's.
BENCHMARK_SCRATCH="$(mktemp -d "${TMPDIR:-/tmp}/dsvire-benchmark.XXXXXX")"
trap 'rm -rf "$BENCHMARK_SCRATCH"' EXIT
export BENCHMARK_SCRATCH
